# Generated by Django 3.2.1 on 2021-05-04 23:09

from django.db import migrations, models
import recetas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ingredientes', models.CharField(max_length=500)),
                ('personas', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to=recetas.models.image_path)),
            ],
        ),
    ]
